accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

workout_tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("workouts/", include("workouts.urls")),
    path("exercises/", include("exercises.urls")),
    path("accounts/", include("accounts.urls")),
    path("", RedirectView.as_view(url="/workouts/"), name="home"),
]

workouts/urls.py
from django.urls import path
from workouts.views import (
    WorkoutListView,
    WorkoutDetailView,
    WorkoutCreateView,
    WorkoutUpdateView,
    WorkoutDeleteView,
    ProudAchievementListView,
    ProudAchievementCreateView,
    ProudAchievementUpdateView,
)


urlpatterns = [
    path("", WorkoutListView.as_view(), name="list_workouts"),
    path("<int:pk>/", WorkoutDetailView.as_view(), name="show_workout"),
    path("create/", WorkoutCreateView.as_view(), name="create_workout"),
    path("<int:pk>/edit/", WorkoutUpdateView.as_view(), name="edit_workout"),
    path(
        "<int:pk>/delete/", WorkoutDeleteView.as_view(), name="delete_workout"
    ),
    path(
        "achievements/",
        ProudAchievementListView.as_view(),
        name="list_achievements",
    ),
    path(
        "create_achievement/",
        ProudAchievementCreateView.as_view(),
        name="create_achievement",
    ),
    path(
        "<int:pk>/edit_achievement/",
        ProudAchievementUpdateView.as_view(),
        name="edit_achievement",
    ),
]

workouts/models.py
from django.db import models
from django.conf import settings


class Workout(models.Model):
    name = models.CharField("Workout", max_length=150)
    description = models.CharField(max_length=200, blank=True, null=True)
    date = models.DateField()
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="workouts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class ProudAchievement(models.Model):
    name = models.CharField("Exercise", max_length=150)
    achievement = models.CharField(max_length=200)
    date = models.DateField()
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="achievements",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

workouts/views.py
from workouts.models import Workout, ProudAchievement
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView,
)
from django.utils.safestring import mark_safe
from django.shortcuts import redirect
from django.urls import reverse_lazy
from .utils import Calendar, get_date, prev_month, next_month
from bootstrap_datepicker_plus.widgets import DatePickerInput


class WorkoutListView(LoginRequiredMixin, ListView):
    model = Workout
    template_name = "workouts/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get("month", None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(self.request.user, withyear=True)
        context["calendar"] = mark_safe(html_cal)
        context["prev_month"] = prev_month(d)
        context["next_month"] = next_month(d)
        return context

    def get_queryset(self):
        d = get_date(self.request.GET.get("month", None))
        return Workout.objects.filter(
            owner=self.request.user,
            date__year=d.year,
            date__month=d.month,
        ).order_by("date")


class WorkoutDetailView(LoginRequiredMixin, DetailView):
    model = Workout
    template_name = "workouts/detail.html"


class WorkoutCreateView(LoginRequiredMixin, CreateView):
    model = Workout
    template_name = "workouts/create.html"
    fields = ["name", "description", "date"]

    def get_form(self):
        form = super().get_form()
        form.fields["date"].widget = DatePickerInput()
        return form

    def form_valid(self, form):
        workout = form.save(commit=False)
        workout.owner = self.request.user
        workout.save()
        return redirect("show_workout", pk=workout.id)


class WorkoutUpdateView(LoginRequiredMixin, UpdateView):
    model = Workout
    template_name = "workouts/edit.html"
    fields = ["name", "description", "date"]

    def get_form(self):
        form = super().get_form()
        form.fields["date"].widget = DatePickerInput()
        return form

    def form_valid(self, form):
        workout = form.save(commit=False)
        workout.owner = self.request.user
        workout.save()
        return redirect("show_workout", pk=workout.id)


class WorkoutDeleteView(LoginRequiredMixin, DeleteView):
    model = Workout
    template_name = "workouts/delete.html"
    success_url = reverse_lazy("list_workouts")


class ProudAchievementListView(LoginRequiredMixin, ListView):
    model = ProudAchievement
    template_name = "workouts/achievement_list.html"

    def get_queryset(self):
        return ProudAchievement.objects.filter(
            owner=self.request.user
        ).order_by("date")


class ProudAchievementCreateView(LoginRequiredMixin, CreateView):
    model = ProudAchievement
    template_name = "workouts/achievement_create.html"
    fields = ["name", "achievement", "date"]

    def get_form(self):
        form = super().get_form()
        form.fields["date"].widget = DatePickerInput()
        return form

    def form_valid(self, form):
        achievement = form.save(commit=False)
        achievement.owner = self.request.user
        achievement.save()
        return redirect("list_achievements")


class ProudAchievementUpdateView(LoginRequiredMixin, UpdateView):
    model = ProudAchievement
    template_name = "workouts/achievement_edit.html"
    fields = ["name", "achievement", "date"]

    def get_form(self):
        form = super().get_form()
        form.fields["date"].widget = DatePickerInput()
        return form

    def get_success_url(self):
        return reverse_lazy("list_achievements")

    def form_valid(self, form):
        if "confirm_delete" in self.request.POST:
            pk = form.instance.pk
            post_delete = ProudAchievement.objects.get(pk=pk)
            post_delete.delete()
        else:
            achievement = form.save(commit=False)
            achievement.owner = self.request.user
            achievement.save()
        return redirect("list_achievements")

workouts/templates/workouts/achievement_create.html
{% extends 'base.html' %} {% block content %} {% load bootstrap4 %}
{%bootstrap_css %} {% bootstrap_javascript jquery='full' %} {{ form.media }}

<div class="form_design">
  <h1>Add Proud Achievement, yay!</h1>
  <form method="POST">
    {% csrf_token %} {% bootstrap_form form %}
    <button class="button_design">Great Job!</button>
  </form>
</div>
{% endblock content %}

workouts/templates/workouts/achievement_edit.html
{% extends 'base.html' %} {% block content %} {% load bootstrap4 %}
{%bootstrap_css %} {% bootstrap_javascript jquery='full' %} {{ form.media }}

<div class="form_design">
  <h1>Edit Proud Achievement</h1>
  <form method="POST">
    {% csrf_token %} {% bootstrap_form form %}
    <button class="button_design">Make Changes</button>
    <input
      class="button_design"
      type="submit"
      name="confirm_delete"
      value="Delete"
    />
  </form>
</div>
{% endblock content %}

workouts/templates/workouts/achievement_list.html
{% extends 'base.html' %} {% block content %}
<h1>Proud Achievements</h1>
<p><a href="{% url 'create_achievement' %}">Add Achievement</a></p>

{% if proudachievement_list|length is 0 %}
<p>You do not have any achievements yet.</p>
{% else %}
<table class="design">
  <thead>
    <tr>
      <th>Exercise</th>
      <th>Achievement</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    {% for achievement in proudachievement_list %}
    <tr>
      <td>
        <a href="{% url 'edit_achievement' achievement.pk %}">
          {{ achievement.name }}
        </a>
      </td>
      <td>{{ achievement.achievement }}</td>
      <td>{{ achievement.date }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endif %} {% endblock content %}

workouts/templates/workouts/create.html
{% extends 'base.html' %} {% block content %} {% load bootstrap4 %}
{%bootstrap_css %} {% bootstrap_javascript jquery='full' %} {{ form.media }}

<div class="form_design">
  <h1>Create New Workout</h1>
  <form method="POST">
    {% csrf_token %} {% bootstrap_form form %}
    <button class="button_design">Create</button>
  </form>
</div>
{% endblock content %}

workouts/templates/workouts/delete.html
{% extends 'base.html' %} {% block content %}
<div class="form_design">
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ workout.name }}"?</p>
    {{ form.as_p }}
    <div class="control">
      <button class="button_design">Delete</button>
    </div>
  </form>
  {% endblock content %}
</div>

workouts/templates/workouts/detail.html
{% extends 'base.html' %} {% block content %}
<h1>{{ workout.name }}</h1>
<p><strong>{{ workout.date }}</strong></p>
{% if workout.description == None %} {% else %}
<p>{{ workout.description }}</p>
{% endif %}
<h2>Exercises</h2>
<p><a href="{% url 'create_exercise' %}">Add Exercise</a></p>
{% if workout.exercises.all|length > 0 %}
<table class="design">
  <thead>
    <tr>
      <th>Exercise</th>
      <th>Target Goal</th>
      <th>Accomplished</th>
    </tr>
  </thead>
  <tbody>
    {% for exercise in workout.exercises.all %}
    <tr>
      <td>
        <a href="{% url 'edit_exercise' exercise.pk %}">{{ exercise.name }}</a>
      </td>
      <td>{{ exercise.target }}</td>
      {% if exercise.accomplished|length == 0 %}
      <td><a href="{% url 'update_exercise' exercise.pk %}">Update</a></td>
      {% else %}
      <td>{{ exercise.accomplished }}</td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>This workout has no exercises!</p>
{% endif %}
<nav class="navigation">
  <li class="nav_item">
    <a href="{% url 'edit_workout' workout.id %}">Edit Workout</a>
  </li>
  <li class="nav_item">
    <a href="{% url 'delete_workout' workout.id %}">Delete Workout</a>
  </li>
</nav>
{% endblock content %}

workouts/templates/workouts/edit.html
{% extends 'base.html' %} {% block content %} {% load bootstrap4 %}
{%bootstrap_css %} {% bootstrap_javascript jquery='full' %} {{ form.media }}
<div class="form_design">
  <h1>Edit Workout</h1>
  <form method="POST">
    {% csrf_token %} {% bootstrap_form form %}
    <button class="button_design">Make Changes</button>
  </form>
</div>
{% endblock content %}

workouts/templates/workouts/list.html
{% extends 'base.html' %} {% block content %}
<h1>My Workouts</h1>
<p><a href="{% url 'create_workout' %}">Create New Workout</a></p>

{{ calendar }}

<div class="navigation">
  <a class="nav_item" href="{% url 'list_workouts' %}?{{ prev_month }}">
    Previous Month
  </a>
  <a class="nav_item" href="{% url 'list_workouts' %}?{{ next_month }}">
    Next Month
  </a>
</div>

{% if workout_list|length is 0 %}
<p>You do not have any workouts.</p>
{% else %}
<table class="design">
  <thead>
    <tr>
      <th>Workout</th>
      <th>Date</th>
      <th>Number of Exercises</th>
    </tr>
  </thead>
  <tbody>
    {% for workout in workout_list %}
    <tr>
      <td>
        <a href="{% url 'show_workout' workout.pk %}">{{ workout.name }}</a>
      </td>
      <td>{{ workout.date }}</td>
      <td>{{ workout.exercises.all|length }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endif %} {% endblock content %}